site_name: ClarityPS
repo_url: https://github.com/jpsider/ClarityPS
theme: readthedocs
edit_uri: edit/master/docs/
pages:
- Home: index.md
- ReportCardPS Basics:
  - What is ReportCardPS: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Public Functions:
  - Invoke-DeployRestPS: NewFunction.md